# Generated by Django 5.1.6 on 2025-02-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('schedule', models.JSONField(help_text='Schedule in the format of days of the week and times', verbose_name='Schedule')),
            ],
        ),
    ]
