# Generated by Django 5.1.6 on 2025-02-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Description'),
        ),
    ]
