# Generated by Django 5.1.6 on 2025-02-17 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_teachers'),
        ('student_groups', '0004_studentgroup_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups_courses', to='courses.course'),
        ),
    ]
