# Generated by Django 5.1.6 on 2025-02-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_groups', '0005_alter_studentgroup_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
