# Generated by Django 5.1.6 on 2025-02-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_date_lesson_teacher_lesson_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.FileField(blank=True, null=True, upload_to='lesson_materials/'),
        ),
    ]
